### PR TITLE
schedule complete

### PR DESCRIPTION
**Pull request by necoline**

### CODE REVIEW

**Comment by suhasdeshpande** [comment]
@necoline, schedule change must be on firebase end right? The way I read this changes, It seems mostly indentation changes. Do you want me to merge them? I am fine with it.

**Comment by necoline** [comment]
you are right, I opened a branch to do some digging, but all of my changes were in firebase

**Comment by suhasdeshpande** [comment]
Do you still want to get this merged then?

**Comment by necoline** [comment]
@suhasdeshpande can you close the branch? I don't see any reason to merge it

**Pull request closed without merging**
